# Generated by Django 5.0.6 on 2024-05-27 15:51

import django.core.validators
import django.db.models.deletion
import products.base.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', products.base.fields.ProductMoneyField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1, 'value must be greater than 1')])),
                ('count', models.SmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('MODERATION', 'Moderation'), ('PUBLISH', 'Publish'), ('CLOSE', 'Close')], default='MODERATION', max_length=20)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOOL', 'Bool'), ('TEXT', 'Text'), ('CHECKBOX', 'Checkbox')], default='TEXT', max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'productAttribute',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('type', 'name'), name='unique_type_name'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_fields_values', to='products.productattribute'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_values', to='products.product'),
        ),
        migrations.AddField(
            model_name='service',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='products.game'),
        ),
        migrations.AddField(
            model_name='product',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_products', to='products.service'),
        ),
    ]
